version: "3.9"

networks:
    isolation-network:
      driver: bridge
  
services:  
    nats_server:
      image: nats-streaming
      container_name: nats_server
      ports:
        - "4222:4222"
        - "8222:8222"
      volumes:
        - ./nats-server:/var/lib/nats
      command:
        - -p
        - '4222'
        - '-m'
        - '8222'
        - '-hbi'
        - '5s'
        - '-hbt'
        - '5s'
        - '-hbf'
        - '2'
        - '-SD'
        - '-cid'
        - 'event-management-nats-cluster'
      networks:
        - isolation-network
      restart: always
      logging:
        driver: none
    auth:
      build: ./auth
      container_name: auth
      ports:
        - "3000:3000"
      volumes:
        - ./auth:/var/lib/auth
      networks:
        - isolation-network
      restart: always
      environment:
        - NATS_CLIENT_ID=auth
        - VIRTUAL_HOST=auth.test.com
      env_file:
        - variables.env
      depends_on:
        - nats_server
    org:
      build: ./org
      container_name: org
      ports:
        - "3001:3000"
      volumes:
        - ./org:/var/lib/org
      networks:
        - isolation-network
      restart: always
      environment:
        - NATS_CLIENT_ID=org
        - VIRTUAL_HOST=org.test.com
      env_file:
        - variables.env
      depends_on:
        - nats_server
    events:
      build: ./events
      container_name: events
      ports:
        - "3002:3000"
      volumes:
        - ./events:/var/lib/events
      networks:
        - isolation-network
      restart: always
      environment:
        - NATS_CLIENT_ID=events
      env_file:
        - variables.env
      depends_on:
        - nats_server
    newsfeed:
      build: ./newsfeed
      container_name: newsfeed
      ports:
        - "3003:3000"
      volumes:
        - ./newsfeed:/var/lib/newsfeed
      networks:
        - isolation-network
      restart: always
      environment:
        - NATS_CLIENT_ID=newsfeed
      env_file:
        - variables.env
      depends_on:
        - nats_server
    participant:
      build: ./participant
      container_name: participant
      ports:
        - "3004:3000"
      volumes:
        - ./participant:/var/lib/participant
      networks:
        - isolation-network
      restart: always
      environment:
        - NATS_CLIENT_ID=participant
      env_file:
        - variables.env
      depends_on:
        - nats_server
    payment:
      build: ./payment
      container_name: payment
      ports:
        - "3005:3000"
      volumes:
        - ./payment:/var/lib/payment
      networks:
        - isolation-network
      restart: always
      environment:
        - NATS_CLIENT_ID=payment
      env_file:
        - variables.env
      depends_on:
        - nats_server