apiVersion: apps/v1
kind: Deployment
metadata:
  name: org-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org
  template:
    metadata:
      labels:
        app: org
    spec:
      containers:
        - name: org
          image: r0m3l/org
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://org-mongo-srv:27017/org"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "event-management-nats-cluster"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: org-srv
spec:
  selector:
    app: org
  ports:
    - name: org
      protocol: TCP
      port: 3000
      targetPort: 3000
